
server:
  port: 8769

spring:
  application:
    name: service-zuul

eureka:
  client:
    security:
      basic:
        user: admin
        password: admin
    service-url:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceid: service-ribbon
    api-b:
      path: /api-b/**
      serviceid: service-feign


