server:
  port: 8763

spring:
  application:
    name: service-hi
  cloud:
    config:
      label: master
 #     profile: dev
      profile: pro
      uri: http://localhost:8888/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
